print("#################################")
print("#                               #")
print("#     Muhammad Firdaus Ilmi     #")
print("#         2610817210001         #")
print("#                               #")
print("#################################")